feat: filter branches for gitlab pages deployment

diff --git a/src/fair_python_cookiecutter/template/{{ cookiecutter.project_slug }}/.gitlab-ci.yml b/src/fair_python_cookiecutter/template/{{ cookiecutter.project_slug }}/.gitlab-ci.yml
--- a/src/fair_python_cookiecutter/template/{{ cookiecutter.project_slug }}/.gitlab-ci.yml
+++ b/src/fair_python_cookiecutter/template/{{ cookiecutter.project_slug }}/.gitlab-ci.yml
@@ -122,16 +122,25 @@ pages:
     HTTPS_REMOTE: https://gitlab-ci-token:${PAGES_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
   <<: *prepare-env
   script:
-  - |
-    if [[ -z "$PAGES_TOKEN" ]]; then
-      echo "ERROR: CI variable PAGES_TOKEN is missing, cannot proceed!"
-      exit 1
-    fi
+  # Preparation: we need to clone the repository in the job and directly access it via git
   - poetry install --with docs
   - git config user.name $GITLAB_USER_NAME
   - git config user.email $GITLAB_USER_EMAIL
   - git fetch origin $PAGES_BRANCH && git -b checkout $PAGES_BRANCH origin/$PAGES_BRANCH || git checkout $PAGES_BRANCH || echo "Pages branch not deployed yet."
   - git checkout $CI_COMMIT_SHA
+  # If triggered by a push, check if the branch is enabled for pages
+  - |
+    if [[ -n "$CI_COMMIT_BRANCH" ]] && ! [[ "$CI_COMMIT_BRANCH" =~ ^(main|dev)$ ]]; then
+      echo "INFO: Branch not enabled for pages, skipping docs deployment ('$PAGES_BRANCH' branch unchanged)."
+      git checkout $PAGES_BRANCH -- public/
+      exit 0
+    fi
+  # Deploy pages for a tag or enabled branch
+  - |
+    if [[ -z "$PAGES_TOKEN" ]]; then
+      echo "ERROR: CI variable PAGES_TOKEN is missing, cannot proceed!"
+      exit 1
+    fi
   - DOCS_TAG_RAW=${CI_COMMIT_TAG:=$CI_COMMIT_BRANCH}  # get tag (or if not present, current branch)
   - DOCS_TAG=${DOCS_TAG_RAW//\//_}  # eliminate '/' symbols from branch (or tag) name
   - echo Deploying docs for "$DOCS_TAG"
